package top.atstudy.advistory.advistory.dao.dto;

import top.atstudy.component.enums.EnumAdvistoryCategory;
import top.atstudy.component.enums.EnumAdvistoryLevel;
import top.atstudy.component.enums.EnumAdvistoryType;
import top.atstudy.component.enums.EnumDeleted;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdvistoryInfoDTOExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    public AdvistoryInfoDTOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AdvistoryInfoDTOExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AdvistoryInfoDTOExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advistory_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AdvistoryInfoDTOExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdvistoryIdIsNull() {
            addCriterion("advistory_id is null");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdIsNotNull() {
            addCriterion("advistory_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdEqualTo(Long value) {
            addCriterion("advistory_id =", value, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdNotEqualTo(Long value) {
            addCriterion("advistory_id <>", value, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdGreaterThan(Long value) {
            addCriterion("advistory_id >", value, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("advistory_id >=", value, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdLessThan(Long value) {
            addCriterion("advistory_id <", value, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdLessThanOrEqualTo(Long value) {
            addCriterion("advistory_id <=", value, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdIn(List<Long> values) {
            addCriterion("advistory_id in", values, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdNotIn(List<Long> values) {
            addCriterion("advistory_id not in", values, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdBetween(Long value1, Long value2) {
            addCriterion("advistory_id between", value1, value2, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryIdNotBetween(Long value1, Long value2) {
            addCriterion("advistory_id not between", value1, value2, "advistoryId");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelIsNull() {
            addCriterion("advistory_level is null");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelIsNotNull() {
            addCriterion("advistory_level is not null");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelEqualTo(EnumAdvistoryLevel value) {
            addCriterion("advistory_level =", value, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelNotEqualTo(EnumAdvistoryLevel value) {
            addCriterion("advistory_level <>", value, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelGreaterThan(EnumAdvistoryLevel value) {
            addCriterion("advistory_level >", value, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelGreaterThanOrEqualTo(EnumAdvistoryLevel value) {
            addCriterion("advistory_level >=", value, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelLessThan(EnumAdvistoryLevel value) {
            addCriterion("advistory_level <", value, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelLessThanOrEqualTo(EnumAdvistoryLevel value) {
            addCriterion("advistory_level <=", value, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelLike(EnumAdvistoryLevel value) {
            addCriterion("advistory_level like", value, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelNotLike(EnumAdvistoryLevel value) {
            addCriterion("advistory_level not like", value, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelIn(List<EnumAdvistoryLevel> values) {
            addCriterion("advistory_level in", values, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelNotIn(List<EnumAdvistoryLevel> values) {
            addCriterion("advistory_level not in", values, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelBetween(EnumAdvistoryLevel value1, EnumAdvistoryLevel value2) {
            addCriterion("advistory_level between", value1, value2, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryLevelNotBetween(EnumAdvistoryLevel value1, EnumAdvistoryLevel value2) {
            addCriterion("advistory_level not between", value1, value2, "advistoryLevel");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryIsNull() {
            addCriterion("advistory_category is null");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryIsNotNull() {
            addCriterion("advistory_category is not null");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryEqualTo(EnumAdvistoryCategory value) {
            addCriterion("advistory_category =", value, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryNotEqualTo(EnumAdvistoryCategory value) {
            addCriterion("advistory_category <>", value, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryGreaterThan(EnumAdvistoryCategory value) {
            addCriterion("advistory_category >", value, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryGreaterThanOrEqualTo(EnumAdvistoryCategory value) {
            addCriterion("advistory_category >=", value, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryLessThan(EnumAdvistoryCategory value) {
            addCriterion("advistory_category <", value, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryLessThanOrEqualTo(EnumAdvistoryCategory value) {
            addCriterion("advistory_category <=", value, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryLike(EnumAdvistoryCategory value) {
            addCriterion("advistory_category like", value, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryNotLike(EnumAdvistoryCategory value) {
            addCriterion("advistory_category not like", value, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryIn(List<EnumAdvistoryCategory> values) {
            addCriterion("advistory_category in", values, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryNotIn(List<EnumAdvistoryCategory> values) {
            addCriterion("advistory_category not in", values, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryBetween(EnumAdvistoryCategory value1, EnumAdvistoryCategory value2) {
            addCriterion("advistory_category between", value1, value2, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryCategoryNotBetween(EnumAdvistoryCategory value1, EnumAdvistoryCategory value2) {
            addCriterion("advistory_category not between", value1, value2, "advistoryCategory");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeIsNull() {
            addCriterion("advistory_type is null");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeIsNotNull() {
            addCriterion("advistory_type is not null");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeEqualTo(EnumAdvistoryType value) {
            addCriterion("advistory_type =", value, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeNotEqualTo(EnumAdvistoryType value) {
            addCriterion("advistory_type <>", value, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeGreaterThan(EnumAdvistoryType value) {
            addCriterion("advistory_type >", value, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeGreaterThanOrEqualTo(EnumAdvistoryType value) {
            addCriterion("advistory_type >=", value, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeLessThan(EnumAdvistoryType value) {
            addCriterion("advistory_type <", value, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeLessThanOrEqualTo(EnumAdvistoryType value) {
            addCriterion("advistory_type <=", value, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeLike(EnumAdvistoryType value) {
            addCriterion("advistory_type like", value, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeNotLike(EnumAdvistoryType value) {
            addCriterion("advistory_type not like", value, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeIn(List<EnumAdvistoryType> values) {
            addCriterion("advistory_type in", values, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeNotIn(List<EnumAdvistoryType> values) {
            addCriterion("advistory_type not in", values, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeBetween(EnumAdvistoryType value1, EnumAdvistoryType value2) {
            addCriterion("advistory_type between", value1, value2, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andAdvistoryTypeNotBetween(EnumAdvistoryType value1, EnumAdvistoryType value2) {
            addCriterion("advistory_type not between", value1, value2, "advistoryType");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDigestIsNull() {
            addCriterion("digest is null");
            return (Criteria) this;
        }

        public Criteria andDigestIsNotNull() {
            addCriterion("digest is not null");
            return (Criteria) this;
        }

        public Criteria andDigestEqualTo(String value) {
            addCriterion("digest =", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotEqualTo(String value) {
            addCriterion("digest <>", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThan(String value) {
            addCriterion("digest >", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThanOrEqualTo(String value) {
            addCriterion("digest >=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThan(String value) {
            addCriterion("digest <", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThanOrEqualTo(String value) {
            addCriterion("digest <=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLike(String value) {
            addCriterion("digest like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotLike(String value) {
            addCriterion("digest not like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestIn(List<String> values) {
            addCriterion("digest in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotIn(List<String> values) {
            addCriterion("digest not in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestBetween(String value1, String value2) {
            addCriterion("digest between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotBetween(String value1, String value2) {
            addCriterion("digest not between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberIsNull() {
            addCriterion("favorite_number is null");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberIsNotNull() {
            addCriterion("favorite_number is not null");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberEqualTo(Long value) {
            addCriterion("favorite_number =", value, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberNotEqualTo(Long value) {
            addCriterion("favorite_number <>", value, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberGreaterThan(Long value) {
            addCriterion("favorite_number >", value, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("favorite_number >=", value, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberLessThan(Long value) {
            addCriterion("favorite_number <", value, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberLessThanOrEqualTo(Long value) {
            addCriterion("favorite_number <=", value, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberIn(List<Long> values) {
            addCriterion("favorite_number in", values, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberNotIn(List<Long> values) {
            addCriterion("favorite_number not in", values, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberBetween(Long value1, Long value2) {
            addCriterion("favorite_number between", value1, value2, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andFavoriteNumberNotBetween(Long value1, Long value2) {
            addCriterion("favorite_number not between", value1, value2, "favoriteNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberIsNull() {
            addCriterion("read_number is null");
            return (Criteria) this;
        }

        public Criteria andReadNumberIsNotNull() {
            addCriterion("read_number is not null");
            return (Criteria) this;
        }

        public Criteria andReadNumberEqualTo(Long value) {
            addCriterion("read_number =", value, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberNotEqualTo(Long value) {
            addCriterion("read_number <>", value, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberGreaterThan(Long value) {
            addCriterion("read_number >", value, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("read_number >=", value, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberLessThan(Long value) {
            addCriterion("read_number <", value, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberLessThanOrEqualTo(Long value) {
            addCriterion("read_number <=", value, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberIn(List<Long> values) {
            addCriterion("read_number in", values, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberNotIn(List<Long> values) {
            addCriterion("read_number not in", values, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberBetween(Long value1, Long value2) {
            addCriterion("read_number between", value1, value2, "readNumber");
            return (Criteria) this;
        }

        public Criteria andReadNumberNotBetween(Long value1, Long value2) {
            addCriterion("read_number not between", value1, value2, "readNumber");
            return (Criteria) this;
        }

        public Criteria andCoverImageIsNull() {
            addCriterion("cover_image is null");
            return (Criteria) this;
        }

        public Criteria andCoverImageIsNotNull() {
            addCriterion("cover_image is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImageEqualTo(String value) {
            addCriterion("cover_image =", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageNotEqualTo(String value) {
            addCriterion("cover_image <>", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageGreaterThan(String value) {
            addCriterion("cover_image >", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageGreaterThanOrEqualTo(String value) {
            addCriterion("cover_image >=", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageLessThan(String value) {
            addCriterion("cover_image <", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageLessThanOrEqualTo(String value) {
            addCriterion("cover_image <=", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageLike(String value) {
            addCriterion("cover_image like", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageNotLike(String value) {
            addCriterion("cover_image not like", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageIn(List<String> values) {
            addCriterion("cover_image in", values, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageNotIn(List<String> values) {
            addCriterion("cover_image not in", values, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageBetween(String value1, String value2) {
            addCriterion("cover_image between", value1, value2, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageNotBetween(String value1, String value2) {
            addCriterion("cover_image not between", value1, value2, "coverImage");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusIsNull() {
            addCriterion("recommend_status is null");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusIsNotNull() {
            addCriterion("recommend_status is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusEqualTo(Boolean value) {
            addCriterion("recommend_status =", value, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusNotEqualTo(Boolean value) {
            addCriterion("recommend_status <>", value, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusGreaterThan(Boolean value) {
            addCriterion("recommend_status >", value, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("recommend_status >=", value, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusLessThan(Boolean value) {
            addCriterion("recommend_status <", value, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("recommend_status <=", value, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusIn(List<Boolean> values) {
            addCriterion("recommend_status in", values, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusNotIn(List<Boolean> values) {
            addCriterion("recommend_status not in", values, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("recommend_status between", value1, value2, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andRecommendStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("recommend_status not between", value1, value2, "recommendStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusIsNull() {
            addCriterion("stick_status is null");
            return (Criteria) this;
        }

        public Criteria andStickStatusIsNotNull() {
            addCriterion("stick_status is not null");
            return (Criteria) this;
        }

        public Criteria andStickStatusEqualTo(Boolean value) {
            addCriterion("stick_status =", value, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusNotEqualTo(Boolean value) {
            addCriterion("stick_status <>", value, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusGreaterThan(Boolean value) {
            addCriterion("stick_status >", value, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("stick_status >=", value, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusLessThan(Boolean value) {
            addCriterion("stick_status <", value, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("stick_status <=", value, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusIn(List<Boolean> values) {
            addCriterion("stick_status in", values, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusNotIn(List<Boolean> values) {
            addCriterion("stick_status not in", values, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("stick_status between", value1, value2, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andStickStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("stick_status not between", value1, value2, "stickStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusIsNull() {
            addCriterion("ad_status is null");
            return (Criteria) this;
        }

        public Criteria andAdStatusIsNotNull() {
            addCriterion("ad_status is not null");
            return (Criteria) this;
        }

        public Criteria andAdStatusEqualTo(Boolean value) {
            addCriterion("ad_status =", value, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusNotEqualTo(Boolean value) {
            addCriterion("ad_status <>", value, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusGreaterThan(Boolean value) {
            addCriterion("ad_status >", value, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ad_status >=", value, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusLessThan(Boolean value) {
            addCriterion("ad_status <", value, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("ad_status <=", value, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusIn(List<Boolean> values) {
            addCriterion("ad_status in", values, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusNotIn(List<Boolean> values) {
            addCriterion("ad_status not in", values, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("ad_status between", value1, value2, "adStatus");
            return (Criteria) this;
        }

        public Criteria andAdStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ad_status not between", value1, value2, "adStatus");
            return (Criteria) this;
        }

        public Criteria andLinkIsNull() {
            addCriterion("link is null");
            return (Criteria) this;
        }

        public Criteria andLinkIsNotNull() {
            addCriterion("link is not null");
            return (Criteria) this;
        }

        public Criteria andLinkEqualTo(String value) {
            addCriterion("link =", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotEqualTo(String value) {
            addCriterion("link <>", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkGreaterThan(String value) {
            addCriterion("link >", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkGreaterThanOrEqualTo(String value) {
            addCriterion("link >=", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLessThan(String value) {
            addCriterion("link <", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLessThanOrEqualTo(String value) {
            addCriterion("link <=", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLike(String value) {
            addCriterion("link like", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotLike(String value) {
            addCriterion("link not like", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkIn(List<String> values) {
            addCriterion("link in", values, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotIn(List<String> values) {
            addCriterion("link not in", values, "link");
            return (Criteria) this;
        }

        public Criteria andLinkBetween(String value1, String value2) {
            addCriterion("link between", value1, value2, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotBetween(String value1, String value2) {
            addCriterion("link not between", value1, value2, "link");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIsNull() {
            addCriterion("publish_user_id is null");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIsNotNull() {
            addCriterion("publish_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdEqualTo(Long value) {
            addCriterion("publish_user_id =", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotEqualTo(Long value) {
            addCriterion("publish_user_id <>", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdGreaterThan(Long value) {
            addCriterion("publish_user_id >", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("publish_user_id >=", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdLessThan(Long value) {
            addCriterion("publish_user_id <", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdLessThanOrEqualTo(Long value) {
            addCriterion("publish_user_id <=", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIn(List<Long> values) {
            addCriterion("publish_user_id in", values, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotIn(List<Long> values) {
            addCriterion("publish_user_id not in", values, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdBetween(Long value1, Long value2) {
            addCriterion("publish_user_id between", value1, value2, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotBetween(Long value1, Long value2) {
            addCriterion("publish_user_id not between", value1, value2, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameIsNull() {
            addCriterion("publish_user_name is null");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameIsNotNull() {
            addCriterion("publish_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameEqualTo(String value) {
            addCriterion("publish_user_name =", value, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameNotEqualTo(String value) {
            addCriterion("publish_user_name <>", value, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameGreaterThan(String value) {
            addCriterion("publish_user_name >", value, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("publish_user_name >=", value, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameLessThan(String value) {
            addCriterion("publish_user_name <", value, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameLessThanOrEqualTo(String value) {
            addCriterion("publish_user_name <=", value, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameLike(String value) {
            addCriterion("publish_user_name like", value, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameNotLike(String value) {
            addCriterion("publish_user_name not like", value, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameIn(List<String> values) {
            addCriterion("publish_user_name in", values, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameNotIn(List<String> values) {
            addCriterion("publish_user_name not in", values, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameBetween(String value1, String value2) {
            addCriterion("publish_user_name between", value1, value2, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishUserNameNotBetween(String value1, String value2) {
            addCriterion("publish_user_name not between", value1, value2, "publishUserName");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeIsNull() {
            addCriterion("publish_operation_time is null");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeIsNotNull() {
            addCriterion("publish_operation_time is not null");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeEqualTo(Date value) {
            addCriterion("publish_operation_time =", value, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeNotEqualTo(Date value) {
            addCriterion("publish_operation_time <>", value, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeGreaterThan(Date value) {
            addCriterion("publish_operation_time >", value, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("publish_operation_time >=", value, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeLessThan(Date value) {
            addCriterion("publish_operation_time <", value, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeLessThanOrEqualTo(Date value) {
            addCriterion("publish_operation_time <=", value, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeIn(List<Date> values) {
            addCriterion("publish_operation_time in", values, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeNotIn(List<Date> values) {
            addCriterion("publish_operation_time not in", values, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeBetween(Date value1, Date value2) {
            addCriterion("publish_operation_time between", value1, value2, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishOperationTimeNotBetween(Date value1, Date value2) {
            addCriterion("publish_operation_time not between", value1, value2, "publishOperationTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNull() {
            addCriterion("publish_time is null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNotNull() {
            addCriterion("publish_time is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeEqualTo(Date value) {
            addCriterion("publish_time =", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotEqualTo(Date value) {
            addCriterion("publish_time <>", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThan(Date value) {
            addCriterion("publish_time >", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("publish_time >=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThan(Date value) {
            addCriterion("publish_time <", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("publish_time <=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIn(List<Date> values) {
            addCriterion("publish_time in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotIn(List<Date> values) {
            addCriterion("publish_time not in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeBetween(Date value1, Date value2) {
            addCriterion("publish_time between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("publish_time not between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIsNull() {
            addCriterion("display_order is null");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIsNotNull() {
            addCriterion("display_order is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderEqualTo(Integer value) {
            addCriterion("display_order =", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotEqualTo(Integer value) {
            addCriterion("display_order <>", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderGreaterThan(Integer value) {
            addCriterion("display_order >", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("display_order >=", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderLessThan(Integer value) {
            addCriterion("display_order <", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderLessThanOrEqualTo(Integer value) {
            addCriterion("display_order <=", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIn(List<Integer> values) {
            addCriterion("display_order in", values, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotIn(List<Integer> values) {
            addCriterion("display_order not in", values, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderBetween(Integer value1, Integer value2) {
            addCriterion("display_order between", value1, value2, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("display_order not between", value1, value2, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(EnumDeleted value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(EnumDeleted value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(EnumDeleted value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(EnumDeleted value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(EnumDeleted value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(EnumDeleted value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<EnumDeleted> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<EnumDeleted> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(EnumDeleted value1, EnumDeleted value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(EnumDeleted value1, EnumDeleted value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNull() {
            addCriterion("create_user_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNotNull() {
            addCriterion("create_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameEqualTo(String value) {
            addCriterion("create_user_name =", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotEqualTo(String value) {
            addCriterion("create_user_name <>", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThan(String value) {
            addCriterion("create_user_name >", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_name >=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThan(String value) {
            addCriterion("create_user_name <", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThanOrEqualTo(String value) {
            addCriterion("create_user_name <=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLike(String value) {
            addCriterion("create_user_name like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotLike(String value) {
            addCriterion("create_user_name not like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIn(List<String> values) {
            addCriterion("create_user_name in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotIn(List<String> values) {
            addCriterion("create_user_name not in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameBetween(String value1, String value2) {
            addCriterion("create_user_name between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotBetween(String value1, String value2) {
            addCriterion("create_user_name not between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(Long value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(Long value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(Long value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(Long value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<Long> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<Long> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(Long value1, Long value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameIsNull() {
            addCriterion("update_user_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameIsNotNull() {
            addCriterion("update_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameEqualTo(String value) {
            addCriterion("update_user_name =", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameNotEqualTo(String value) {
            addCriterion("update_user_name <>", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameGreaterThan(String value) {
            addCriterion("update_user_name >", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_name >=", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameLessThan(String value) {
            addCriterion("update_user_name <", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameLessThanOrEqualTo(String value) {
            addCriterion("update_user_name <=", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameLike(String value) {
            addCriterion("update_user_name like", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameNotLike(String value) {
            addCriterion("update_user_name not like", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameIn(List<String> values) {
            addCriterion("update_user_name in", values, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameNotIn(List<String> values) {
            addCriterion("update_user_name not in", values, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameBetween(String value1, String value2) {
            addCriterion("update_user_name between", value1, value2, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameNotBetween(String value1, String value2) {
            addCriterion("update_user_name not between", value1, value2, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNull() {
            addCriterion("last_update is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNotNull() {
            addCriterion("last_update is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateEqualTo(Date value) {
            addCriterion("last_update =", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotEqualTo(Date value) {
            addCriterion("last_update <>", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThan(Date value) {
            addCriterion("last_update >", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update >=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThan(Date value) {
            addCriterion("last_update <", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThanOrEqualTo(Date value) {
            addCriterion("last_update <=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIn(List<Date> values) {
            addCriterion("last_update in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotIn(List<Date> values) {
            addCriterion("last_update not in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateBetween(Date value1, Date value2) {
            addCriterion("last_update between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotBetween(Date value1, Date value2) {
            addCriterion("last_update not between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}